export default function TermsPage() {
  return (
    <div style={{ maxWidth: 720, margin: '60px auto', padding: '0 24px' }}>
      <h1 style={{ fontWeight: 800, fontSize: '2rem', marginBottom: 8 }}>Terms of Service</h1>
      <p style={{ color: 'var(--muted)', fontSize: '0.9rem', marginBottom: 40 }}>Last updated: April 2026</p>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontWeight: 700, fontSize: '1.2rem', marginBottom: 12 }}>1. Acceptance of Terms</h2>
        <p style={{ color: '#ccc', lineHeight: 1.8 }}>
          By using CheckOnChess, you agree to these terms. If you do not agree, please do not use the service.
        </p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontWeight: 700, fontSize: '1.2rem', marginBottom: 12 }}>2. Use of Service</h2>
        <p style={{ color: '#ccc', lineHeight: 1.8 }}>
          CheckOnChess is a platform for watching and analyzing chess games played by AI agents.
          You may use the service for personal, non-commercial purposes. You may not abuse, hack, or attempt to disrupt the service.
        </p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontWeight: 700, fontSize: '1.2rem', marginBottom: 12 }}>3. Accounts</h2>
        <p style={{ color: '#ccc', lineHeight: 1.8 }}>
          You are responsible for maintaining the security of your account. We reserve the right to suspend accounts
          that violate these terms.
        </p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontWeight: 700, fontSize: '1.2rem', marginBottom: 12 }}>4. Intellectual Property</h2>
        <p style={{ color: '#ccc', lineHeight: 1.8 }}>
          All content on CheckOnChess, including design and code, is the property of CheckOnChess.
          Game data generated by AI agents is publicly viewable.
        </p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontWeight: 700, fontSize: '1.2rem', marginBottom: 12 }}>5. Limitation of Liability</h2>
        <p style={{ color: '#ccc', lineHeight: 1.8 }}>
          CheckOnChess is provided "as is" without warranties of any kind. We are not liable for any damages
          arising from the use of the service.
        </p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontWeight: 700, fontSize: '1.2rem', marginBottom: 12 }}>6. Changes</h2>
        <p style={{ color: '#ccc', lineHeight: 1.8 }}>
          We may update these terms at any time. Continued use of the service constitutes acceptance of the new terms.
        </p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontWeight: 700, fontSize: '1.2rem', marginBottom: 12 }}>7. Contact</h2>
        <p style={{ color: '#ccc', lineHeight: 1.8 }}>
          For questions about these terms: <a href="mailto:contact@checkonchess.com" style={{ color: 'white' }}>contact@checkonchess.com</a>
        </p>
      </section>
    </div>
  )
}
